#!/usr/bin/env bun
/**
 * Regenerate the forked SPEC.md from upstream + DELTA.md, and refresh upstream.lock.json.
 *
 * Usage: bun run spec:build
 */

import { dirname, resolve } from "node:path";
import { applyDelta, loadContext, sha256, upstreamCommit } from "./delta.ts";

const root = resolve(dirname(Bun.fileURLToPath(import.meta.url)), "..");

try {
  const ctx = await loadContext(root);
  const result = await applyDelta(ctx.upstream, ctx.delta, root);

  await Bun.write(ctx.outputPath, result.output);

  const lock = {
    _comment:
      "Generated by tools/spec-build.ts. Pins the upstream spec this fork was built against. See RULES.md 6.",
    upstream: ctx.delta.meta.upstream,
    upstream_sha256: sha256(ctx.upstream),
    upstream_commit: await upstreamCommit(ctx.upstreamPath),
    output: ctx.delta.meta.output,
    output_sha256: sha256(result.output),
    delta_entries: ctx.delta.entries.map((e) => e.id),
  };
  await Bun.write(ctx.lockPath, `${JSON.stringify(lock, null, 2)}\n`);

  const markerTotal = [...result.markers.values()].reduce((a, b) => a + b, 0);
  console.log(
    `spec:build ok — ${ctx.delta.entries.length} delta entries, ${markerTotal} markers, ` +
      `${result.output.split("\n").length} lines`,
  );
} catch (error) {
  console.error(`spec:build failed\n  ${(error as Error).message}`);
  process.exit(1);
}
